language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
scripts:
  - cargo build --all-features
  - cargo test --all-features
  - cargo doc --all-features

deploy:
  provider: cargo
  token: $CARGO_API_TOKEN
  on:
   tags: true
   rust: stable