language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - windows
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true
scripts:
  - cargo build --all-features
  - cargo test --all-features

deploy:
  provider: cargo
  token: $CARGO_API_TOKEN
  on:
   tags: true
   rust: stable
   os: linux